### PR TITLE
Fix for GitHub branch URLs in automations (0.15)

### LINKED ISSUE #65: Apply command doesn't respect branches on transform
When supplying a branch such as "automation" or "development" to the `bridgetown apply` command, it appends "master"

**Bridgetown Version**:

0.15.0.beta-2

**Current Behavior**:

```bash
bridgetown apply https://github.com/ParamagicDev/bridgetown-plugin-tailwindcss/tree/automation/bridgetown.automation.rb
```

Turns 

"https://github.com/ParamagicDev/bridgetown-plugin-tailwindcss/tree/automation/bridgetown.automation.rb" 

into 

"https://raw.githubusercontent.com/ParamagicDev/bridgetown-plugin-tailwindcss/automation/master/bridgetown.automation.rb"

**Expected Behavior**

"https://github.com/ParamagicDev/bridgetown-plugin-tailwindcss/tree/automation/bridgetown.automation.rb" 

Should turn to

"https://raw.githubusercontent.com/ParamagicDev/bridgetown-plugin-tailwindcss/automation/bridgetown.automation.rb"

### PR DESCRIPTION
**Pull request by ParamagicDev**
This is a 🐛 bug fix.

  - I've added tests (if it's a bug, feature or enhancement)
  - The test suite passes locally (run `script/cibuild` to verify this)

## Summary

My pull request allow you to use a branch for the command "apply"

It transforms the Github url to one that allows the use of a branch

IE: 

`https://github.com/bridgetownrb/bridgetown/tree/automations`

turns to

`https://raw.githubusercontent.com/bridgetownrb/bridgetown/automations/bridgetown.automation.rb`

## Context

Fixes #65

### CODE REVIEW

**Comment by ParamagicDev** [comment]
I added a `require bundler` to actions because it was failing locally for me without the require statement.

It said `NameError: uninitialized constant Bridgetown::Commands::Apply::Bundler`

**Comment by jaredcwhite** [comment]
Terrific! I'll dig into this later today 👍

File: bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb [hunk 1]
```diff
@@ -77,23 +77,34 @@ def apply_from_url(url)
...
 
-        remote_file = if arg.end_with?(".rb")
-                        arg.split("/").yield_self do |segments|
-                          arg.sub!(%r!/#{segments.last}$!, "")
-                          segments.last
-                        end
-                      else
-                        "bridgetown.automation.rb"
-                      end
+        remote_file = remote_file(arg)
```
Comment (jaredcwhite) [inline bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb:95]: I generally prefer to name local variables differently than methods so there's no confusion. Not sure what makes sense here…would love suggestions.

File: bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb [hunk 2]
```diff
@@ -77,23 +77,34 @@ def apply_from_url(url)
...
 
         if arg.start_with?("https://gist.github.com")
           return arg.sub(
             "https://gist.github.com", "https://gist.githubusercontent.com"
           ) + "/raw/#{remote_file}"
+        elsif match
+          return arg.sub(
+            tree_regex, "https://raw.githubusercontent.com"
+          ) + "/#{match[:path]}/#{match[:branch]}/#{remote_file}"
         elsif arg.start_with?("https://github.com")
```
Comment (jaredcwhite) [inline bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb:108]: Do we need still need to check GitHub with `start_with?` if we're doing the match above?

File: bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb (hunk 1 above)
Comment (ParamagicDev) [reply bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb:95]: Honestly, I only did this to make rubocop happy. Could name it something like `find_remote_filename(arg)` and then do 

`remote_file = find_remote_filename(arg)`

Comment (jaredcwhite) [reply bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb:95]: How about `determine_remote_filename`

File: bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb (hunk 2 above)
Comment (ParamagicDev) [reply bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb:108]: The match above wont match with a regular master branch because it doesnt include `tree`.

However, we could make a base regex for github:

IE:

```ruby
github_regex = %r!https://github\.com!
```

And then use Regex concatenation to drop it into the tree regex like so:

```ruby
github_tree_regex = %r!#{github_regex}/(?<path>.*/.*)/tree/(?<branch>.*)/?!
```

First we want to run the matches up front before we mess with the URL.
Then we will always replace Github on github_regex match
Something like the following:

```ruby
github_match = github_regex.match(arg)
github_tree_match = github_tree_regex.match(arg)

elsif github_match
  new_url = arg.sub(github_regex, "https://raw.githubusercontent.com")
  
  return new_url + "/master/#{remote_file}" if github_tree_match.nil?

  return new_url + "/#{match[:path]}/#{match[:branch]}/#{remote_file}"
end
```

Comment (ParamagicDev) [reply bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb:108]: On further review, we actually dont need the `match[:path]` we could simple do `#{match[:branch}/#{remote_file}`

Comment (jaredcwhite) [reply bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb:108]: That sounds like a good approach to me. Can you go ahead and update your branch with the conditional logic consolidated like that? 👍

File: bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb (hunk 1 above)
Comment (ParamagicDev) [reply bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb:95]: sounds good, ill make it happen.

File: bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb (hunk 2 above)
Comment (ParamagicDev) [reply bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb:108]: Absolutely, working on it now, the issue I'm running into is I have to sub "/tree/" but I dont want to run the risk of having the user have a directory named `/tree/` so it may be slightly more complicated than expected. Ill add a test for making sure you dont conflic with a `/tree/` directory.

**Comment by jaredcwhite** [comment]
Wow, the logic for this is badass…took me a while even to grok how it was working, so bravo. 👏 Merging!
